yolo_model:

  video_file:
    name: /root/catkin_ws/src/tkDNN/demo/yolo_test.mp4
  weights_file:
    name: /root/catkin_ws/src/tkDNN/build/yolo4tiny_fp32.rt
  threshold:
    value: 0.5
  detection_classes:
    value: 80
